version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build:
    docker:
      - image: 'circleci/node:14.17.6'
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: sudo npm install -g npm@latest
      - run: npx eslint 'src/**'
      - run: npm run test
workflows:
  dev:
    jobs:
      - development
