version: '2.1'
orbs:
  node: circleci/node@5.0.0
  coveralls: coveralls/coveralls@1.0.4
jobs:
  development:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: sudo npm install -g npm@latest
      - run: npx eslint 'src/**'
      - run: npm run test
      - coveralls/upload:
          path_to_lcov: ./coverage/lcov.info
workflows:
  dev:
    jobs:
      - development